DROP TABLE IF EXISTS dictionary;

CREATE TABLE learn_dutch_1000
(
  word_id INTEGER PRIMARY KEY AUTOINCREMENT,
  dic_id INTEGER NOT NULL
);

CREATE TABLE dictionary
(
  word_id INTEGER PRIMARY KEY AUTOINCREMENT,
  dutch TEXT NOT NULL UNIQUE,
  example TEXT NOT NULL,
  note TEXT
);

CREATE TABLE user (
  user_id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  password TEXT NOT NULL
);

